### PR TITLE
microverse tse pull request

### PR DESCRIPTION
**Pull request by firmoholanda**

### CODE REVIEW

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes Required 🛑 
@firmoholanda You have done a great job related to UI and Readme But there are some validation errors
- html validation errors
image
- css validation errors
image
- [Optional] 🎏 You can use `<main>` tag for the dominant content of the <body> of a document
- [Optional] 🎏 No need to wrap `<nav>` tag with `<article>`, try to avoid it.
#### Don't forgot to request for another code review

**Pon Muthu Selvam N**
Feel free contact me 
[Github //@imhta](https://github.com/imhta) | [Twitter //@nponmuthuselvam](https://twitter.com/ponmuthuselvam)

**Comment by firmoholanda** [comment]
thanks for the reply, validated the html and css. no errors now.

**Review by Forison — COMMENTED** [review]
# Pull request under review by Addo

**Review by Forison — APPROVED** [review]
# Hi @firmoholanda,
## The page looks great💪 
Go ahead and merge to master
# Project approved💪 
## happy coding

**Pull request merged**
